export const ADD_TODO_IN_LIST_STARTED = 'ADD_TODO_IN_LIST_STARTED';
export const ADD_TODO_IN_LIST_SUCCESS = 'ADD_TODO_IN_LIST_SUCCESS';
export const ADD_TODO_IN_LIST_ERROR = 'ADD_TODO_IN_LIST_ERROR';

export const FETCH_TODO_LIST_STARTED = 'FETCH_TODO_LIST_STARTED';
export const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS';
export const FETCH_TODO_LIST_ERROR = 'FETCH_TODO_LIST_ERROR';

export const SET_POPUP_MENU_ACTIVE = 'SET_POPUP_MENU_ACTIVE';
export const SET_POPUP_DELETE_TODO_ACTIVE = 'SET_POPUP_DELETE_TODO_ACTIVE';

export const UPDATE_TODO_STARTED = 'UPDATE_TODO_STARTED';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const SET_EDITING_ID = 'SET_EDITING_ID';

export const DELETE_TODO_STARTED = 'DELETE_TODO_STARTED';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
